name: run-timer-bot
on:
  schedule:
    - cron: '5 */2 * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Run bot
        env:
          TARGET_LINK: ${{ secrets.TARGET_LINK }}
        run: python main.py
